### ISSUE TITLE
Region() method crashes if SDC_URL has a trailing '/'

### ISSUE THREAD

**Issue by sodre** [joyent/gosign#8]
Steps to reproduce:

- `export SDC_URL="http://us-east-1.api.joyentcloud.com/"`
- Run anything that depends on gosign, .e.g. terraform scripts.
- Receive something like
```console
panic: runtime error: slice bounds out of range

goroutine 50 [running]:
panic(0x72db80, 0xc82000e0d0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/terraform/vendor/github.com/joyent/gosign/auth.(*Credentials).Region(0xc82035b720, 0x0, 0x0)
	/Users/sodre/go/src/github.com/hashicorp/terraform/vendor/github.com/joyent/gosign/auth/auth.go:122 +0x11c
github.com/hashicorp/terraform/vendor/github.com/joyent/gocommon/http.getDateForRegion(0xc82035b720, 0x818700, 0x0, 0x0)
	/Users/sodre/go/src/github.com/hashicorp/terraform/vendor/github.com/joyent/gocommon/http/client.go:135 +0x169
github.com/hashicorp/terraform/vendor/github.com/joyent/gocommon/http.createHeaders(0x0, 0xc82035b720, 0x8938b0, 0x10, 0x0, 0x0, 0x81eb10, 0x4, 0x0, 0xe, ...)
	/Users/sodre/go/src/github.com/hashicorp/terraform/vendor/github.com/joyent/gocommon/http/client.go:116 +0x4e6
github.com/hashicorp/terraform/vendor/github.com/joyent/gocommon/http.(*Client).JsonRequest(0xc82035f680, 0x819f00, 0x4, 0xc82038
...
```

A fix is to have the code in Region use a URL parsing library instead of looking for the last '/'.

**Comment by twhiteman** [comment]
Thanks - updated to make use of the "net/url" package and check slice bounds.
